config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("9bimz3i7gdc8mtq/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("recipies/", include("recipies.urls", namespace="recipies")),
    path("users/", include("users.urls", namespace="users")),
    url(r"media/(?P<path>.*)$", serve,
        {"document_root": settings.MEDIA_ROOT, }),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("home", views.home, name="home"),
    path("", views.LoginView.as_view(), name="login"),
]

foods/urls.py
from django.urls import path
from . import views


app_name = "foods"

urlpatterns = [
    path("<int:pk>/", views.food_detail, name="food_detail"),
    path("register/", views.FoodRegisterView.as_view(), name="register"),
    path("update/<int:pk>", views.food_update, name="update"),
    path("list/", views.food_list, name="list"),
    path("delete/<int:pk>/", views.food_delete, name="delete"),
]

recipies/urls.py
from django.urls import path
from . import views

app_name = "recipies"

urlpatterns = [
    path("list/<int:pk>/", views.recipe_list, name="recipe_list"),
    path("detail/<int:pk>/", views.recipe_detail, name="recipe_detail"),
    path("create/", views.recipe_create, name="register"),
    path("update/<int:pk>/", views.recipe_update, name="update"),
    path("mylist/<int:pk>/", views.my_recipe, name="mylist"),
    path("worldcup/", views.recipe_worldcup, name="worldcup"),
    path("delete/<int:pk>/", views.recipe_delete, name="delete"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),

    path("update/<int:pk>", views.profile_update, name="profile-update"),

]

templates/partials/bottom_menu.html
<div class="bottom_menus">
    <div class="menu_wrap dot_icon jsDot" onclick="clickDotIcon(event)">
        <i class="fas fa-ellipsis-h menu_dot jsI"></i>
    </div>
    <a href="{% url 'foods:register' %}" class="menu_wrap write_icon jsWrite">
        <i style="font-size:1.5rem;" class="fas fa-plus menu_dot"></i>
    </a>
    <a href="{% url 'recipies:register'%}" class="menu_wrap how_icon jsHow">
        <i class="fas fa-utensils menu_dot"></i>
    </a>
</div>

templates/partials/header.html
{% load static %}
<a href="{% url 'core:home' %}">
    <div class="header_title">
        <img src="{% static '/core/img/title.png' %}" alt="title">
        <span class="header_text">이것<span style="color:red;">좀</span>먹어줘</span>
    </div>
</a>

templates/partials/hidden_menu.html
<div class="jsHiddenMenu hidden_menu">
    <div class="menu_top">
    </div>
    <div class="menu_middle">
        <a href="{% url 'foods:list' %}" class="menu_middle_menus">등록한 식자재</a>
        <a href="{% url 'recipies:mylist' user.pk %}" class="menu_middle_menus">내가 만든 레시피</a>
        <a href="{% url 'recipies:recipe_list' user.pk %}" class="menu_middle_menus">추천 레시피</a>
        <a href="{% url 'foods:register' %}" class="menu_middle_menus">식자재 등록</a>
        <a href="{% url 'recipies:register' %}" class="menu_middle_menus">레시피 등록</a>
        <a href="{% url 'recipies:worldcup' %}" class="menu_middle_menus">레시피 월드컵</a>
    </div>
    <div class="menu_bottom">
        <a href="{% url 'users:logout' %}"><i class="fas fa-power-off power-off"></i></a>
        <a href="{% url 'users:profile-update' user.pk %}"><i class="fas fa-cog cog"></i></a>

    </div>
</div>

templates/partials/messages.html
{% if messages %}
<ul class="msg_big">
    {% for message in messages %}
    <li class="msg" class="{% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load static %}
<i class="fas fa-bars jsMenu"></i>

templates/partials/paginator.html
<div class="paginator">
    <div class="page_center">
        {% for page in paginator.page_range %}
        {% if sort %}
        <a href="?page={{page}}&sort={{sort}}">
            <div class="page">
                {{page}}
            </div>
        </a>
        {% else %}
        <a href="?page={{page}}">
            <div class="page">
                {{page}}
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
</div>