config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("9bimz3i7gdc8mtq/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("recipies/", include("recipies.urls", namespace="recipies")),
    path("users/", include("users.urls", namespace="users")),
    url(r"media/(?P<path>.*)$", serve,
        {"document_root": settings.MEDIA_ROOT, }),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("home", views.home, name="home"),
    path("", views.LoginView.as_view(), name="login"),
]

recipies/urls.py
from django.urls import path
from . import views

app_name = "recipies"

urlpatterns = [
    path("list/<int:pk>/", views.recipe_list, name="recipe_list"),
    path("detail/<int:pk>/", views.recipe_detail, name="recipe_detail"),
    path("create/", views.recipe_create, name="register"),
    path("update/<int:pk>/", views.recipe_update, name="update"),
    path("mylist/<int:pk>/", views.my_recipe, name="mylist"),
    path("worldcup/", views.recipe_worldcup, name="worldcup"),
    path("delete/<int:pk>/", views.recipe_delete, name="delete"),
]

recipies/models.py
from django.db import models
from .my_crawling import gogogo
from users import models as user_models
from django.utils import timezone
from django_random_queryset import RandomManager
import os
import random


def photo_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    return 'recipies/{randomstring}{ext}'.format(basename=basefilename, randomstring=randomstr, ext=file_extension)


class Recipe(models.Model):
    EASY = "쉬움"
    SOSO = "중급"
    HARD = "어려움"
    LEVEL_CHOICES = (
        (EASY, "쉬움"),
        (SOSO, "중급"),
        (HARD, "어려움"),
    )

    name = models.CharField(max_length=100, null=True)
    photo = models.ImageField(upload_to=photo_path, default="default.png")

    how_to_create = models.TextField(max_length=10000, null=True)
    recipe_quantity = models.IntegerField(null=True)
    recipe_time = models.IntegerField(null=True)
    recipe_level = models.CharField(
        max_length=30, choices=LEVEL_CHOICES, null=True)
    creator = models.ForeignKey(
        user_models.User, related_name="creators", on_delete=models.CASCADE, blank=True, null=True)
    objects = RandomManager()

    def total_rating(self):
        total_rating = 0
        for rating in self.comments.all():
            total_rating = total_rating + int(rating.rating)
        try:
            total_rating = total_rating/self.comments.count()
            return round(total_rating, 2)
        except ZeroDivisionError:
            return 0

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if RecipeLink.objects.filter(recipe=self).exists():
            RecipeLink.objects.filter(recipe=self).delete()
        links = gogogo(self.name)
        for link in links:
            new_link_obj = RecipeLink(name=link, recipe=self)
            new_link_obj.save()


class FoodInRecipe(models.Model):
    name = models.CharField(max_length=100, null=True)
    recipe = models.ForeignKey(
        "Recipe", on_delete=models.CASCADE, blank=True, null=True, related_name="foods")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.replace(" ", "")
        super().save(*args, **kwargs)


class RecipeLink(models.Model):
    name = models.CharField(max_length=50)
    recipe = models.ForeignKey(
        Recipe, related_name="links", on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class RecipePercent(models.Model):
    user = models.ForeignKey(
        user_models.User, related_name="percents", on_delete=models.CASCADE)
    recipe = models.ForeignKey(
        Recipe, related_name="percents", on_delete=models.CASCADE)
    percent = models.IntegerField()


class Comment(models.Model):
    STA1 = 1
    STA2 = 2
    STA3 = 3
    STA4 = 4
    STA5 = 5
    STAR_CHOICES = (
        ("1", 1),
        ("2", 2),
        ("3", 3),
        ("4", 4),
        ("5", 5),
    )
    user = models.ForeignKey(
        user_models.User, related_name="comments", on_delete=models.CASCADE)
    recipe = models.ForeignKey(
        "Recipe", related_name="comments", on_delete=models.CASCADE)
    create_time = models.DateField(auto_now=True)
    rating = models.CharField(
        max_length=10, choices=STAR_CHOICES, default=5)
    body = models.TextField(max_length=100)

    def time_turm(self):
        time_turm = timezone.localtime().date() - self.create_time
        time_turm = time_turm.days
        if time_turm > 0:
            return f"{time_turm}일 전"
        else:
            return "오늘"

recipies/forms.py
from django import forms
from . import models


class RecipeCreateForm(forms.ModelForm):
    class Meta:
        model = models.Recipe
        fields = (
            "photo",
            "name",
            "how_to_create",
            "recipe_quantity",
            "recipe_time",
            "recipe_level",
        )
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "레시피명"}),
            "subname": forms.TextInput(attrs={"placeholder": "부제목"}),
            "how_to_create": forms.Textarea(attrs={"placeholder": "조리방법을 작성 해 주세요!", "class": "how_to_create"}),
            "recipe_time": forms.NumberInput(attrs={"placeholder": "조리시간(분)", "style": "-webkit-appearance:none;"}),
            "recipe_level": forms.Select()
        }
    need_food = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "식자재"}),
    )


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ("rating", "body")
        widgets = {
            "rating": forms.Select(attrs={"class": "comment_select"}),
            "body": forms.Textarea(attrs={"placeholder": "댓글을 입력해주세요", "class": "comment_textarea"}),
        }

recipies/views.py
from . import my_crawling
from django.shortcuts import render, redirect, reverse
from django.db.models import Count
from django.core.paginator import Paginator
from users import models as users_model
from . import models as recipies_model
from . import forms
from django.utils.html import mark_safe


def recipe_list(request, pk):
    user = users_model.User.objects.get(pk=pk)
    user_foods = user.foods.all()
    user_food_list = []
    for food in user.foods.all():
        user_food_list.append(food.name)
    reco_recipe = recipies_model.Recipe.objects.all()
    resulted_reco_recipe = []
    reco_food_percent = []
    for reco_food in reco_recipe:
        food_list = []
        count = 0
        reco_food_len = 0
        print(reco_food)
        print(reco_food.foods.all())
        print(user_food_list)
        for food in reco_food.foods.all():
            count = count + user_food_list.count(food.name)
            reco_food_len = reco_food_len + 1
        if count/reco_food_len >= 0:
            reco_per = int((count/reco_food_len)*100)
            reco_food_percent.append(reco_per)
            resulted_reco_recipe.append(reco_food.name)
    recipes = reco_recipe.filter(name__in=resulted_reco_recipe)
    count = 0
    for recipe in recipes:
        try:
            percent_model = recipies_model.RecipePercent.objects.get(
                user=request.user, recipe=recipe)
            percent_model.percent = reco_food_percent[count]
            percent_model.save()
        except recipies_model.RecipePercent.DoesNotExist:
            percent_model = recipies_model.RecipePercent.objects.create(
                user=request.user, recipe=recipe, percent=reco_food_percent[count])
            percent_model.save()
        count = count + 1
    how_show = 6
    paginator = Paginator(recipes, how_show)
    page_number = request.GET.get("page")
    paged_recipes = paginator.get_page(page_number)

    context = {
        "user": user,
        "recipes": recipes,
        "paged_recipes": paged_recipes,
        "paginator": paginator,
        "page_number": page_number,
        "how_show": how_show,
        "percent": reco_food_percent,
        "percent_list_len": len(reco_food_percent)
    }
    return render(request, "recipies/recipe_list.html", context)


def recipe_detail(request, pk):
    result_foods = []
    user = users_model.User.objects.get(pk=request.user.pk)
    user_foods = user.foods.all()
    user_food_list = []
    for food in user.foods.all():
        user_food_list.append(food.name)

    recipe = recipies_model.Recipe.objects.get(pk=pk)
    recipe_food_list = []
    for food in recipe.foods.all():
        recipe_food_list.append(food.name)

    for food in recipe_food_list:
        if food in user_food_list:
            result_foods.append(
                mark_safe(f"<i class='fas fa-check'></i><span>{food}</span>"))
        else:
            result_foods.append(
                mark_safe(f"<i class='fas fa-times ex'></i><span>{food}</span>"))

    percent = recipies_model.RecipePercent.objects.get(
        user=request.user, recipe=recipe)

    if request.method == 'POST':
        form = forms.CommentCreateForm(request.POST)
        if form.is_valid():
            comment = recipies_model.Comment()
            comment.user = request.user
            comment.recipe = recipe
            comment.rating = form.cleaned_data.get('rating')
            comment.body = form.cleaned_data.get('body')
            comment.save()
    else:
        form = forms.CommentCreateForm()

    return render(request, "recipies/recipe_detail.html", {"recipe": recipe, "result": result_foods, "percent": percent.percent, "form": form})


def recipe_create(request):
    if request.method == 'POST':
        form = forms.RecipeCreateForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = recipies_model.Recipe()
            recipe.name = form.cleaned_data.get('name')
            recipe.photo = form.cleaned_data.get('photo')
            recipe.how_to_create = form.cleaned_data.get('how_to_create')
            recipe.recipe_quantity = form.cleaned_data.get('recipe_quantity')
            recipe.recipe_time = form.cleaned_data.get('recipe_time')
            recipe.recipe_level = form.cleaned_data.get('recipe_level')
            recipe.creator = request.user
            recipe.save()

            need_food = request.POST.getlist('need_food')

            for food in need_food:
                new_food = recipies_model.FoodInRecipe(
                    name=food, recipe=recipe)
                new_food.save()
            return redirect(reverse('recipies:recipe_list', kwargs={'pk': request.user.pk}))

    else:
        form = forms.RecipeCreateForm()

    return render(request, 'recipies/recipe_form.html', {'form': form})


def recipe_update(request, pk):
    recipe = recipies_model.Recipe.objects.get(pk=pk)
    infood_counts = recipe.foods.all().count()
    infoods = []
    for food in recipe.foods.all():
        infoods.append(food.name.replace('"', "").replace("'", ""))
    if request.method == 'POST':
        form = forms.RecipeCreateForm(
            request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe.name = form.cleaned_data.get('name')
            recipe.photo = form.cleaned_data.get('photo')
            recipe.how_to_create = form.cleaned_data.get('how_to_create')
            recipe.recipe_quantity = form.cleaned_data.get('recipe_quantity')
            recipe.recipe_time = form.cleaned_data.get('recipe_time')
            recipe.recipe_level = form.cleaned_data.get('recipe_level')
            recipe.save()

            recipe.foods.all().delete()

            need_food = request.POST.getlist('need_food')

            for food in need_food:
                new_food = recipies_model.FoodInRecipe(
                    name=food, recipe=recipe)
                new_food.save()

            return redirect(reverse('recipies:recipe_detail', kwargs={'pk': pk}))
    else:
        form = forms.RecipeCreateForm(instance=recipe)

    return render(request, 'recipies/recipe_update.html', {'form': form, "recipe": recipe, "photo_url": recipe.photo.url, 'infoods': infoods, "infood_counts": infood_counts})


def my_recipe(request, pk):
    user = users_model.User.objects.get(pk=pk)
    user_foods = user.foods.all()
    user_food_list = []
    for food in user.foods.all():
        user_food_list.append(food.name)
    reco_recipe = recipies_model.Recipe.objects.filter(creator=request.user)
    resulted_reco_recipe = []
    reco_food_percent = []
    for reco_food in reco_recipe:
        food_list = []
        count = 0
        reco_food_len = 0
        for food in reco_food.foods.all():
            count = count + user_food_list.count(food.name)
            reco_food_len = reco_food_len + 1
        if count/reco_food_len >= 0:
            reco_per = int((count/reco_food_len)*100)
            reco_food_percent.append(reco_per)
            resulted_reco_recipe.append(reco_food.name)
    recipes = reco_recipe.filter(name__in=resulted_reco_recipe)
    count = 0
    for recipe in recipes:
        try:
            percent_model = recipies_model.RecipePercent.objects.get(
                user=request.user, recipe=recipe)
            percent_model.percent = reco_food_percent[count]
            percent_model.save()
        except recipies_model.RecipePercent.DoesNotExist:
            percent_model = recipies_model.RecipePercent.objects.create(
                user=request.user, recipe=recipe, percent=reco_food_percent[count])
            percent_model.save()
        count = count + 1
    how_show = 6
    paginator = Paginator(recipes, how_show)
    page_number = request.GET.get("page")
    paged_recipes = paginator.get_page(page_number)

    context = {
        "user": user,
        "recipes": recipes,
        "paged_recipes": paged_recipes,
        "paginator": paginator,
        "page_number": page_number,
        "how_show": how_show,
        "percent": reco_food_percent,
        "percent_list_len": len(reco_food_percent)
    }
    return render(request, "recipies/my_recipe.html", context)


def recipe_worldcup(request):
    all_recipes = recipies_model.Recipe.objects.all()
    random_picked_recipes = all_recipes.random(8)
    count = 0

    for x in random_picked_recipes:
        if count == 0:
            r0 = x
        elif count == 1:
            r1 = x
        elif count == 2:
            r2 = x
        elif count == 3:
            r3 = x
        elif count == 4:
            r4 = x
        elif count == 5:
            r5 = x
        elif count == 6:
            r6 = x
        elif count == 7:
            r7 = x
        count = count + 1

    return render(request, 'recipies/recipe_worldcup.html', {"r0": r0, "r1": r1, "r2": r2, "r3": r3, "r4": r4, "r5": r5, "r6": r6, "r7": r7, })


def recipe_delete(request, pk):
    recipe = recipies_model.Recipe.objects.get(pk=pk)
    recipe.delete()

    return redirect(reverse("recipies:mylist", kwargs={'pk': request.user.pk}))

templates/recipies/recipe_form.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}
레시피 등록
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
<link rel="stylesheet" href="{% static '/foods/css/food_upload_image.css' %}" type="text/css">
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<style>
    .menu_middle_menus {
        font-size: 1.8rem;
    }

    .how_to_create {
        width: 27rem;
        height: 6rem;
        padding: 0.5rem;
        font-size: 1.5rem;
        font-weight: bold;
        border-color: #ffeed4 !important;
        border-width: medium;
        border-radius: 5px;
        resize: none;
        font-family: "NanumSquare", sans-serif;
        overflow: hidden;
    }

    .how_to_create:focus {
        outline: none;
    }

    .how_to_create::placeholder {
        color: #ffd779;
        display: flex;
        align-items: center;
    }


    body {
        background-color: white;
    }

    .file-upload {
        height: 200px;
    }

    .two_button {
        display: inline-block;
        margin-top: 10px;
    }

    .file-upload-content {}

    .file-upload-image {
        margin: 0 0;
        width: 100px;
        height: 100px;
        display: inline-block;
    }

    .drag-text {
        height: 170px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .drag-text h3 {
        padding: 0;
    }

    .image-upload-wrap {
        margin-top: 0;
        height: 170px;
    }

    .input select {
        padding: 0.5rem;
        font-size: 1.5rem;
        font-weight: bold;
        border-color: #ffeed4 !important;
        border-width: medium;
        border-radius: 5px;
        background-color: #fff4e2;
        color: #ffb300;
    }

    .input select:focus {
        outline: none;
    }

    .input select:hover {
        cursor: pointer;
    }

    select option {
        font-family: "NanumSquare", sans-serif !important;
    }

    input,
    select {
        font-weight: normal !important;
    }

    .need_food {
        width: 32%;
        display: inline-block;
        margin-right: 1.3%;
    }

    .need_food input {
        width: 100%;
    }

    .need_food_big {
        width: 95%;
        flex-direction: row;
        justify-content: flex-start !important;
    }

    .input {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
    }

    input,
    .quantity_input,
    textarea,
    .file-upload,
    select {
        width: 95% !important;
    }

    .please_input {
        width: 100% !important;
    }

    .wrapper {
        position: relative;
        margin-top: 4rem;
        height: auto;
    }

    @media(max-width:500px) {
        .wrapper {
            position: static;
            margin-top: 15rem;
        }
    }

    .need_plus {
        padding: 0.3rem;
        display: flex;
        flex-direction: row;
        justify-content: flex-start !important;
        font-size: 2.2rem;
        color: #ff8100;
    }

    .need_plus i:hover {
        cursor: pointer;
    }

    @media(max-height:750px) {
        .wrapper {
            margin-top: 20rem;
        }
    }
</style>
{% endblock css %}


{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}
    {% for field in form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">
        {% if field.name == 'photo' %}
        <div class="file-upload">

            <div class="image-upload-wrap">
                <input class="file-upload-input" type='file' name="photo" onchange="readURL(this);" accept="image/*"
                    id="id_photo" />
                <div class="drag-text">
                    <h3>클릭하거나 드래그하여 사진을 업로드 하세요!</h3>
                </div>
            </div>
            <div class="file-upload-content">
                <img class="file-upload-image" src="#" alt="your image" />
                <div class="two_button">
                    <button class="login_btn file-upload-btn " type="button"
                        onclick="$('.file-upload-input').trigger( 'click' )">이미지
                        변경</button>

                </div>
            </div>
        </div>
        {% elif field.name == 'recipe_quantity' %}
        <div class="input quantity_input">
            <div class="jsLeft wrap_caret"><i class="fas fa-minus caret"></i></div>
            <input class="jsQuantity q1" type="number" name="recipe_quantity" placeholder="인분" required=""
                id="id_recipe_quantity">
            <div class="jsRight wrap_caret"><i class="fas fa-plus caret"></i></div>
        </div>
        {% elif field.name == 'recipe_level' %}
        <select name="recipe_level" required id="id_recipe_level">
            <option selected disabled value="">난이도 선택</option>

            <option value="쉬움">쉬움</option>

            <option value="중급">중급</option>

            <option value="어려움">어려움</option>

        </select>
        {% elif field.name == 'need_food' %}
        <div class="input need_food_big">
            <div class="input need_food jsNeed">
                <input class="please_input" type="text" name="need_food" placeholder="식자재" required id="id_need_food">
            </div>
            <div class="input need_food">
                <input class="please_input" type="text" name="need_food" placeholder="식자재">
            </div>
            <div class="input need_food need_plus">
                <i class="fas fa-plus-square jsNeedPlus"></i>
            </div>
        </div>
        {% else %}
        {{field}}
        {% endif %}
        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button class="login_btn jsSubmit">레시피 등록</button>
</form>
{% endblock content %}

{% block script %}
<script src="{% static '/foods/js/food_upload_image.js' %}"></script>
<script src="{% static '/foods/js/quantity_button.js' %}"></script>
<script src="{% static '/recipies/js/need_food_add.js' %}"></script>
{% endblock script %}

templates/recipies/recipe_update.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}
레시피 수정
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
<link rel="stylesheet" href="{% static '/foods/css/food_upload_image.css' %}" type="text/css">
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<style>
    .menu_middle_menus {
        font-size: 1.8rem;
    }

    .how_to_create {
        width: 27rem;
        height: 6rem;
        padding: 0.5rem;
        font-size: 1.5rem;
        font-weight: bold;
        border-color: #ffeed4 !important;
        border-width: medium;
        border-radius: 5px;
        resize: none;
        font-family: "NanumSquare", sans-serif;
        overflow: hidden;
    }

    .how_to_create:focus {
        outline: none;
    }

    .how_to_create::placeholder {
        color: #ffd779;
        display: flex;
        align-items: center;
    }


    body {
        background-color: white;
    }

    .file-upload {
        height: 200px;
    }

    .two_button {
        display: inline-block;
        margin-top: 10px;
    }

    .file-upload-content {}

    .file-upload-image {
        margin: 0 0;
        width: 100px;
        height: 100px;
        display: inline-block;
    }

    .drag-text {
        height: 170px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .drag-text h3 {
        padding: 0;
    }

    .image-upload-wrap {
        margin-top: 0;
        height: 170px;
    }

    .input select {
        padding: 0.5rem;
        font-size: 1.5rem;
        font-weight: bold;
        border-color: #ffeed4 !important;
        border-width: medium;
        border-radius: 5px;
        background-color: #fff4e2;
        color: #ffb300;
    }

    .input select:focus {
        outline: none;
    }

    .input select:hover {
        cursor: pointer;
    }

    select option {
        font-family: "NanumSquare", sans-serif !important;
    }

    input,
    select {
        font-weight: normal !important;
    }

    .need_food {
        width: 32%;
        display: inline-block;
        margin-right: 1.3%;
    }

    .need_food input {
        width: 100%;
    }

    .need_food_big {
        width: 95%;
        flex-direction: row;
        justify-content: flex-start !important;
    }

    .input {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
    }

    input,
    .quantity_input,
    textarea,
    .file-upload,
    select {
        width: 95% !important;
    }

    .please_input {
        width: 100% !important;
    }

    .wrapper {
        position: relative;
        margin-top: 4rem;
        height: auto;
    }

    @media(max-width:500px) {
        .wrapper {
            position: static;
            margin-top: 15rem;
        }
    }

    .need_plus {
        padding: 0.3rem;
        display: flex;
        flex-direction: row;
        justify-content: flex-start !important;
        font-size: 2.2rem;
        color: #ff8100;
    }

    .need_plus i:hover {
        cursor: pointer;
    }

    @media(max-height:750px) {
        .wrapper {
            margin-top: 20rem;
        }
    }

    /*
    *
    이미지프리뷰부분
    *
    */
    .update_img_box {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 0.5rem;
        padding-bottom: 1.3rem;
    }

    .profile_avatar {
        border-radius: 50%;
        width: 10rem;
        height: 10rem;
    }

    #id_photo {
        border: none;
    }

    input #file-upload-button {
        background-color: red;
    }

    .upload-btn-wrapper {
        position: relative;
        overflow: hidden;
        text-align: center;
        padding: 0 0.5rem;
    }

    .avatar-update-btn {
        border: none;
        border-radius: 5px;
        background-color: #ff3b3b;
        color: white;
        font-weight: bold;
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        font-family: "NanumSquare", sans-serif;
    }

    #id_photo:hover {
        cursor: pointer;
    }

    .upload-btn-wrapper input[type=file] {
        font-size: 100px;
        position: absolute;
        left: 0;
        top: 0;
        opacity: 0;
    }
</style>
{% endblock css %}


{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}
    {% for field in form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">
        {% if field.name == 'photo' %}
        <div class="input ">
            <div class="update_img_box">
                <img class="profile_avatar" src="{{photo_url}}" id="image_section" alt="photo" />
            </div>
            <div class="upload-btn-wrapper">
                <input type="file" name="photo" accept="image/*" id="id_photo">
                <button class="avatar-update-btn">이미지 변경</button>
            </div>
        </div>
        {% elif field.name == 'recipe_quantity' %}
        <div class="input quantity_input">
            <div class="jsLeft wrap_caret"><i class="fas fa-minus caret"></i></div>
            <input value="{{recipe.recipe_quantity}}" class="jsQuantity q1" type="number" name="recipe_quantity"
                placeholder="인분" required="" id="id_recipe_quantity">
            <div class="jsRight wrap_caret"><i class="fas fa-plus caret"></i></div>
        </div>
        {% elif field.name == 'recipe_level' %}
        <select name="recipe_level" required id="id_recipe_level">
            <option disabled value="">난이도 선택</option>

            {% if recipe.recipe_level == '쉬움' %}
            <option selected value="쉬움">쉬움</option>
            {% else %}
            <option value="쉬움">쉬움</option>
            {% endif %}

            {% if recipe.recipe_level == '중급' %}
            <option selected value="중급">중급</option>
            {% else %}
            <option value="중급">중급</option>
            {% endif %}

            {% if recipe.recipe_level == '어려움' %}
            <option selected value="어려움">어려움</option>
            {% else %}
            <option value="어려움">어려움</option>
            {% endif %}

        </select>
        {% elif field.name == 'need_food' %}
        <div class="input need_food_big">
            <div class="input need_food need_plus">
                <i class="fas fa-plus-square jsNeedPlus"></i>
            </div>
        </div>
        {% else %}
        {{field}}
        {% endif %}
        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button class="login_btn jsSubmit">레시피 등록</button>
</form>
{% endblock content %}

{% block script %}
<script src="{% static '/foods/js/food_upload_image.js' %}"></script>
<script src="{% static '/foods/js/quantity_button.js' %}"></script>
<script src="{% static '/recipies/js/need_food_add.js' %}"></script>
<script src="{% static '/recipies/js/image_preview.js' %}"></script>
<script>
    const infood_counts = "{{infood_counts}}";
    let infoods = "{{infoods}}";
    function replaceAll(str, searchStr, replaceStr) {
        return str.split(searchStr).join(replaceStr);
    }
    infoods = infoods.replace(";", "");
    infoods = infoods.replace("[", "");
    infoods = infoods.replace("]", "");
    infoods = replaceAll(infoods, ";", "");
    infoods = replaceAll(infoods, "'", "");
    infoods = replaceAll(infoods, ";", "");
    infoods = replaceAll(infoods, "&#x27", "");
    infoods = replaceAll(infoods, " ", "");
    infoods = infoods.split(',');

    const updateDefaultNeedFoods = () => {
        for (const x of infoods) {
            x = x.replaceAll(x, "'", "");
            gijun.insertAdjacentHTML(
                "beforebegin",
                `
                <div class="input need_food">
                    <input value="${x}" class="please_input" type="text" name="need_food" placeholder="식자재">
                </div>
                `
            );
        }
    };

    updateDefaultNeedFoods();

</script>
{% endblock script %}