config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("9bimz3i7gdc8mtq/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("recipies/", include("recipies.urls", namespace="recipies")),
    path("users/", include("users.urls", namespace="users")),
    url(r"media/(?P<path>.*)$", serve,
        {"document_root": settings.MEDIA_ROOT, }),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("home", views.home, name="home"),
    path("", views.LoginView.as_view(), name="login"),
]

foods/urls.py
from django.urls import path
from . import views


app_name = "foods"

urlpatterns = [
    path("<int:pk>/", views.food_detail, name="food_detail"),
    path("register/", views.FoodRegisterView.as_view(), name="register"),
    path("update/<int:pk>", views.food_update, name="update"),
    path("list/", views.food_list, name="list"),
    path("delete/<int:pk>/", views.food_delete, name="delete"),
]

foods/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import mark_safe
from users import models as users_models
from . import models as foods_models
from . import my_validator
import os
import random


# Create your models here.
def photo_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    return 'enrolled_food/{userid}/{randomstring}{ext}'.format(userid=instance.user.id, basename=basefilename, randomstring=randomstr, ext=file_extension)


class HowToUseFood(models.Model):
    name = models.CharField(max_length=100)
    how_to_trim = models.TextField(max_length=10000, null=True)
    how_to_store = models.TextField(max_length=10000, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.replace(" ", "")
        super().save(*args, **kwargs)


class Food(models.Model):
    name = models.CharField(max_length=20)
    photo = models.ImageField(upload_to=photo_path, default="default.png")
    expired_date = models.DateField(null=False)
    quantity = models.PositiveIntegerField(null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(
        users_models.User, related_name="foods", on_delete=models.CASCADE
    )

    def short_name(self):
        if len(self.name) > 6:
            return self.name[:7] + ".."
        else:
            return self.name

    def count_date(self):
        cal_date = self.expired_date - timezone.localtime().date()
        cal_date = cal_date.days
        if cal_date > 0:
            return f"{cal_date}일 남음"
        elif cal_date == 0:
            return "오늘까지"
        else:
            return mark_safe(f"<span style='color:red;'>{abs(cal_date)}일 지남</span>")

        # cal_date = str(cal_date)

        # if cal_date[0] == "-":
        #     return mark_safe(f"<span style='color:red;'>{cal_date[1]}일 지남</span>")
        # else:
        #     if cal_date[0] == "0":
        #         return "오늘까지"
        #     elif int(cal_date[0]) > 0:
        #         return f"{cal_date[0]}일 남음"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.replace(" ", "")
        super().save(*args, **kwargs)

foods/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput
from . import models


class FoodRegisterForm(forms.ModelForm):
    class Meta:
        model = models.Food
        fields = (
            "name",
            "photo",
            "expired_date",
            "quantity",
        )
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "식자재명"}),
            "expired_date": DatePickerInput(
                attrs={"placeholder": "유통기한 마감일"},
                options={"format": "YYYY-MM-DD"},
            ),
            "quantity": forms.NumberInput(attrs={"placeholder": "갯수"}),
        }

foods/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django import forms as django_forms
from users import models as users_model
from core import mixins
from . import models as foods_model, forms


# Create your views here.


def food_list(request):
    if request.user.is_anonymous:
        return redirect(reverse("core:login"))
    page = request.GET.get("page")
    sort = request.GET.get('sort', '')
    if sort == 'mypost':  # 등록순
        food_list = foods_model.Food.objects.filter(user=request.user.pk)
    elif sort == 'quantity':  # 잔량순
        food_list = foods_model.Food.objects.filter(
            user=request.user.pk).order_by('-quantity')
    else:  # 유통기한 마감일순, 디폴트 정렬
        food_list = foods_model.Food.objects.filter(
            user=request.user.pk).order_by('expired_date')
    paginator = Paginator(food_list, 9)
    foods = paginator.get_page(page)
    context = {"foods": foods, "paginator": paginator, 'sort': sort}
    return render(request, "foods/food_list.html", context)


def food_detail(request, pk):
    try:
        food = foods_model.Food.objects.get(pk=pk)
    except foods_model.Food.DoesNotExist:
        return redirect(reverse("core:home"))
    if food.user != request.user:
        return redirect(reverse("core:login"))
    food_data = foods_model.HowToUseFood.objects.all()
    how_to_trim = ""
    how_to_store = ""
    try:
        equal_food = food_data.get(name=food)
        how_to_trim = equal_food.how_to_trim
        how_to_store = equal_food.how_to_store
    except:
        pass
    context = {
        "food": food,
        "how_to_trim": how_to_trim,
        "how_to_store": how_to_store,
    }
    return render(request, "foods/food_detail.html", context)


class FoodRegisterView(CreateView, mixins.LoggedInOnlyView):
    model = foods_model.Food
    form_class = forms.FoodRegisterForm
    success_url = reverse_lazy("core:home")
    context_object_name = "my_form"

    def form_valid(self, form):
        food = form.save(commit=False)
        my_food = foods_model.Food.objects.filter(user=self.request.user.pk)
        filtered_food = my_food.filter(name=food.name)
        if filtered_food:
            form.add_error("name", "이미 존재하는 식자재입니다")
            return self.form_invalid(form)
        else:
            food.user = self.request.user
            food.save()
            return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = None
        if self.request.user.is_anonymous:
            return redirect(reverse("core:login"))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FoodRegisterView, self).get_context_data(**kwargs)
        context["my_form"] = context["form"]
        return context


def food_update(request, pk):
    food = foods_model.Food.objects.get(pk=pk)
    if request.method == "POST":
        form = forms.FoodRegisterForm(request.POST, instance=food)
        if form.is_valid():
            food = form.save()
            return redirect('foods:list')

    else:
        form = forms.FoodRegisterForm(instance=food)

    return render(request, 'foods/food_update.html', {'my_form': form})


def food_delete(request, pk):
    food = foods_model.Food.objects.get(pk=pk)
    food.delete()
    return redirect(reverse("foods:list"))

templates/foods/food_detail.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
{{food}}
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static 'foods/css/food_detail.css' %}" type="text/css">
{% endblock css %}



{% block content %}
<div class="content_area">
    <div class="detail_edit_box">
        <a href="{% url 'foods:update' food.pk %}"><i class="fas fa-pen-square"></i></a>
    </div>
    <img class="food_img" src="{{food.photo.url}}" alt="img">
    <p class="food_name">{{food.name}}</p>
    <hr class="recipe_hr">

    <div class="food_infobox">
        <div class="food_quantity_box">
            <img class="quantity_img" src="{% static 'core/img/quantity.png' %}">
            <p class="quantity_text">{{food.quantity}}개 남음</p>
        </div>
        <div class="food_time_box">
            <img class="time_img" src="{% static 'core/img/clock.png' %}">
            <p class="time_text">{{food.count_date}}</p>
        </div>
    </div>

    <div class="food_detail_text">
        {% if how_to_store %}
        <p class="food_store_title">| 식자재 보관법</p>
        <div class="food_store_text">
            <p>{{how_to_store|linebreaks}}</p>
        </div>
        <p class="food_trim_title">| 식자재 손질법</p>
        <div class="food_trim_text">
            <p>{{how_to_trim|linebreaks}}</p>
        </div>

        {% endif %}
        <a href=javascript:history.go(-1)>
            <img class="back_img" src="{% static 'core/img/back_button.png' %}" alt="img">
        </a>
    </div>
</div>

{% endblock content %}


{% block script %}

{% endblock script %}

templates/foods/food_form.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}
식자재 등록
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
<link rel="stylesheet" href="{% static '/foods/css/food_upload_image.css' %}" type="text/css">
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<style>
    .menu_middle_menus {
        font-size: 1.8rem;
    }
</style>
{% load bootstrap4 %} {# import bootstrap4 / bootstrap3 #}
{% bootstrap_css %} {# 임베디드 부트 스트랩 CSS #}
{% bootstrap_javascript jquery='full'%} {# 부트 스트랩 JS + jQuery #}
{{form.media}}
{% endblock css %}


{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if my_form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}
    {% for field in my_form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">
        {% if field.name == 'photo' %}
        <div class="file-upload">

            <div class="image-upload-wrap">
                <input class="file-upload-input" type='file' name="photo" onchange="readURL(this);" accept="image/*"
                    id="id_photo" />
                <div class="drag-text">
                    <h3>클릭하거나 드래그하여 사진을 업로드 하세요!</h3>
                </div>
            </div>
            <div class="file-upload-content">
                <img class="file-upload-image" src="#" alt="your image" />
                <div class="two_button">
                    <button class="login_btn file-upload-btn " type="button"
                        onclick="$('.file-upload-input').trigger( 'click' )">이미지
                        변경</button>

                </div>
            </div>
        </div>
        {% elif field.name == 'expired_date' %}
        {{ field }}
        {% elif field.name == 'quantity' %}
        <div class="input quantity_input">
            <div class="jsLeft wrap_caret"><i class="fas fa-minus caret"></i></div>
            <input value="1" class="jsQuantity q1" type="number" name="quantity" placeholder="갯수" required=""
                id="id_quantity">
            <div class="jsRight wrap_caret"><i class="fas fa-plus caret"></i></div>
        </div>
        {% else %}
        {{field}}
        {% endif %}
        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button class="login_btn">식자재 등록</button>
</form>
{% endblock content %}

{% block script %}
<script src="{% static '/foods/js/food_upload_image.js' %}"></script>
<script src="{% static '/foods/js/quantity_button.js' %}"></script>
{% endblock script %}

templates/foods/food_list.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
식자재 리스트
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static 'foods/css/food_list.css' %}" type="text/css">
{% endblock css %}


{% block content %}
{% if foods %}
<div class="big_select">
    <select id="sort-select" onchange="location = this.value;">

        {% if sort == 'mypost'  %}
        <option class="sort-date" value="?sort">유통기한순</option>
        <option class="sort-quantity" value="?sort=quantity">잔량순</option>
        <option class="sort-mypost" value="?sort=mypost" selected>등록순</option>
        {% elif sort == 'quantity' %}
        <option class="sort-date" value="?sort">유통기한순</option>
        <option class="sort-quantity" value="?sort=quantity" selected>잔량순</option>
        <option class="sort-mypost" value="?sort=mypost">등록순</option>
        {% else %}
        <option class="sort-date" value="?sort" selected>유통기한순</option>
        <option class="sort-quantity" value="?sort=quantity">잔량순</option>
        <option class="sort-mypost" value="?sort=mypost">등록순</option>
        {% endif %}
    </select>
</div>
<div class="food_list">
    {% for food in foods %}
    <div class="food_card">
        <div class="card_xbox">
            <a href="{% url 'foods:delete' food.pk %}"><i class="fas fa-minus-circle"></i></a>
        </div>
        <a href="{% url 'foods:food_detail' food.pk %}"><img class="food_img" src="{{food.photo.url}}" alt="img"></a>
        <a href="{% url 'foods:food_detail' food.pk %}"><span class="food_title">{{food.short_name}}</span></a>
        <a href="{% url 'foods:food_detail' food.pk %}"><span>잔량 : {{food.quantity}}개</span></a>
        <a href="{% url 'foods:food_detail' food.pk %}"><span>유통기한 : {{food.count_date}}</span></a>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="big_does_not_exist">
    <span class="food_does_not_exist">아직 등록된 식자재가 없습니다</span>
</div>
{% endif %}


{% include "partials/paginator.html" %}

{% endblock content %}

templates/foods/food_update.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}
식자재 등록
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
<link rel="stylesheet" href="{% static '/foods/css/food_upload_image.css' %}" type="text/css">
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
{% load bootstrap4 %} {# import bootstrap4 / bootstrap3 #}
{% bootstrap_css %} {# 임베디드 부트 스트랩 CSS #}
{% bootstrap_javascript jquery='full'%} {# 부트 스트랩 JS + jQuery #}
{{form.media}}
{% endblock css %}


{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if my_form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}
    {% for field in my_form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">
        {% if field.name == 'photo' %}
        <div style="opacity:0; position:absolute;">{{field}}</div>
        {% elif field.name == 'expired_date' %}
        {{ field }}
        {% elif field.name == 'quantity' %}
        <div class="input quantity_input">
            <div class="jsLeft wrap_caret"><i class="fas fa-minus caret"></i></div>
            <input value="1" class="jsQuantity q1" type="number" name="quantity" placeholder="갯수" required=""
                id="id_quantity">
            <div class="jsRight wrap_caret"><i class="fas fa-plus caret"></i></div>
        </div>
        {% else %}
        {{field}}
        {% endif %}
        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button class="login_btn">식자재 등록</button>
</form>
{% endblock content %}

{% block script %}
<script src="{% static '/foods/js/food_upload_image.js' %}"></script>
<script src="{% static '/foods/js/quantity_button.js' %}"></script>
{% endblock script %}