config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("9bimz3i7gdc8mtq/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("recipies/", include("recipies.urls", namespace="recipies")),
    path("users/", include("users.urls", namespace="users")),
    url(r"media/(?P<path>.*)$", serve,
        {"document_root": settings.MEDIA_ROOT, }),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("home", views.home, name="home"),
    path("", views.LoginView.as_view(), name="login"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),

    path("update/<int:pk>", views.profile_update, name="profile-update"),

]

users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
import os
import random

# Create your models here.


def photo_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    return 'avatar/{userid}/{randomstring}{ext}'.format(userid=instance.id, basename=basefilename, randomstring=randomstr, ext=file_extension)


class User(AbstractUser):
    LOGIN_EMAIL = "email"
    LOGIN_KAKAO = "kakao"
    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_KAKAO, "Kakao"),
    )

    email_verified = models.BooleanField(default=True)
    email_secret = models.CharField(max_length=120, default="", blank=True)
    nickname = models.CharField(max_length=100, null=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )
    email_verified = models.BooleanField(default=True)
    avatar = models.ImageField(
        upload_to=photo_path, default="avatar_default.png")

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify PLZEAT Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

    def __str__(self):
        return self.username

    def save(self, udt=True, social_login=True, *args, **kwargs):
        if (udt is True) or (social_login is True):
            pass
        else:
            splited = self.email.split("@")
            splited = splited[0]
            self.nickname = splited
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from . import models
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):

    email = forms.EmailField(
        widget=forms.TextInput(attrs={"placeholder": "이메일 주소"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    "password", forms.ValidationError("비밀번호가 틀렸습니다"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("계정이 존재하지 않습니다"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("email",)
        widgets = {
            "email": forms.TextInput(attrs={"placeholder": "이메일 주소"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호 재확인"}),
        label="Confirm Password",
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        print(email)
        try:
            user = models.User.objects.get(email=email)
            raise forms.ValidationError("계정이 이미 존재합니다")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            return password

    def save(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = super().save(commit=False)
        user.username = email
        listed_email = email.split("@")
        user.nickname = listed_email[0]
        user.set_password(password)
        user.save()


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("avatar", "email", "nickname",)
        widgets = {
            "email": forms.TextInput(attrs={"placeholder": "이메일", "readonly": "readonly", "class": "update_email"}),
            "nickname": forms.TextInput(attrs={"placeholder": "닉네임"}),
        }
        labels = {
            'email': _('이메일'),
            'nickname': _('닉네임'),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호(선택)"}),
        label='비밀번호',
        required=False,
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 재확인(선택)"}),
        label="비밀번호 재확인",
        required=False,
    )

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            return password

users/views.py
import os
import requests
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import FormView
from django.contrib import messages
from core import mixins
from . import forms, models

# Create your views here.


def log_out(request):
    logout(request)
    return redirect(reverse("core:login"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        print(email)
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, f"환영합니다, {user.nickname}님!")
        # user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do success message
    except models.User.DoesNotExist:
        # to do error message
        pass
    return redirect(reverse("core:home"))


#### 소셜 로그인 ####
def kakao_login(request):
    client_id = "e72f124e5a2a725a6aee644df5be6a83"
    redirect_uri = "http://plzeat.eba-z5f66ryb.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = "e72f124e5a2a725a6aee644df5be6a83"
        redirect_uri = "http://plzeat.eba-z5f66ryb.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        kakao_account = profile_json.get("kakao_account")
        email = kakao_account.get("email", None)
        properties = profile_json.get("properties")
        nickname = properties.get("nickname")
        if email is None:
            email = f"{nickname}@plzeat.com"
        profile_image = properties.get("profile_image")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(
                    f"Please login with: {user.login_method}.")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                nickname=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save(social_login=True)
            # if profile_image is not None:
            #     photo_request = requests.get(profile_image)
            #     user.avatar.save(
            #         f"{nickname}-avatar", ContentFile(photo_request.content)
            #     )
        messages.success(request, f"환영합니다, {user.nickname}님!")
        login(request, user)
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("core:login"))


def profile_update(request, pk):
    try:
        user = models.User.objects.get(pk=pk)
    except models.User.DoesNotExist:
        messages.error(request, "접근할 수 없습니다")
        return redirect(reverse('core:home'))
    if user != request.user:
        messages.error(request, "접근할 수 없습니다")
        return redirect(reverse('core:home'))
    if request.method == 'POST':
        form = forms.ProfileUpdateForm(
            request.POST, request.FILES, instance=user)
        if form.is_valid():
            user.avatar = form.cleaned_data.get("avatar")
            user.nickname = form.cleaned_data.get("nickname")
            print(form.cleaned_data.get("password") == "")
            if form.cleaned_data.get("password") != "":
                user.set_password(form.cleaned_data.get("password"))
            user.save(udt=True)
            messages.success(request, f"회원정보가 수정되었습니다")
            return redirect(reverse('core:home'))

    else:
        form = forms.ProfileUpdateForm(instance=user)

    return render(request, 'users/profile_update.html', {"form": form})

templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
Login
{% endblock page_title %}


{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
{% endblock css %}


{% block header %}{% endblock header %}

{% block content %}
<form class="login_form" method="POST" action="{% url 'core:login' %}">
    {% csrf_token %}

    {% if form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}
    <a href="{% url 'users:kakao-login' %}">
        <div class="social_login">
            <i class="fas fa-comment mr-1"></i>
            <span>카카오 계정으로 로그인</span>
        </div>
    </a>
    <div class="or_line">
        <hr>
        <span>or</span>
        <hr>
    </div>
    {% for field in form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">
        {{field}}
        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>

    {% endfor %}
    <button class="login_btn">로그인</button>
    <hr class="login_hr">
    <div class="go_to_signup">
        <span class="login_ask_have">계정이 없으세요?</span>
        <a href="{% url 'users:signup' %}"><span class="signup_link">회원 가입</span></a>
    </div>

</form>
{% endblock content %}
{% block bottom_menu %}{% endblock bottom_menu %}

templates/users/profile_update.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
Profile Update
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
<style>
    body {
        background-color: #ffcd7a91;
    }

    .wrapper {
        padding-top: 0;
        position: relative;
        top: 5vh;
        height: 80vh;
    }

    .menu_middle_menus {
        font-size: 1.8rem;
    }

    i {
        font-size: 2rem !important;
    }

    .update_img_box {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 0.5rem;
        padding-bottom: 1.3rem;
    }

    .profile_avatar {
        border-radius: 50%;
        width: 10rem;
        height: 10rem;
    }

    #id_avatar {
        border: none;
    }

    input #file-upload-button {
        background-color: red;
    }

    .upload-btn-wrapper {
        position: relative;
        overflow: hidden;
        text-align: center;
        padding: 0 0.5rem;
    }

    .avatar-update-btn {
        border: none;
        border-radius: 5px;
        background-color: #ff3b3b;
        color: white;
        font-weight: bold;
        padding: 0.5rem 1rem;
        font-size: 1.5rem;
        font-family: "NanumSquare", sans-serif;
    }

    #id_avatar:hover {
        cursor: pointer;
    }

    .upload-btn-wrapper input[type=file] {
        font-size: 100px;
        position: absolute;
        left: 0;
        top: 0;
        opacity: 0;
    }

    .fa-bars {
        font-size: 2.75rem !important;
    }


    @media (min-width: 500px) {
        .wrapper {
            height: 95vh;
            top: 15vh;
            padding-top: 1.5rem;
        }
    }

    @media (max-height: 750px) {
        .wrapper {
            top: 15vh;
            height: 90vh;
            width: 90%;
            margin-bottom: 2rem;
        }
    }
</style>
{% endblock css %}


{% block content %}
<form style="margin: 0 1rem;" class="login_form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}

    {% for field in form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">

        {% if field.name == 'avatar'  %}
        <div class="input ">
            <div class="update_img_box">
                <img class="profile_avatar" src="{{user.avatar.url}}" id="image_section" alt="avatar" />
            </div>
            <div class="upload-btn-wrapper">
                <input type="file" name="avatar" accept="image/*" id="id_avatar">
                <button class="avatar-update-btn">이미지 변경</button>
            </div>
        </div>
        {% else %}
        <span style="font-weight: bold; font-size: 1.1rem">{{field.label}}</span>
        {{field}}
        {% endif %}

        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>

    {% endfor %}
    <button class="login_btn">회원정보 수정</button>

</form>
{% endblock content %}

{% block script %}
<script src="{% static 'users/js/image_preview.js' %}"></script>
{% endblock script %}

templates/users/signup.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
Sign Up
{% endblock page_title %}

{% block css %}
<link rel="stylesheet" href="{% static '/users/css/login.css' %}" type="text/css">
{% endblock css %}

{% block header %}{% endblock header %}

{% block content %}
<form class="login_form" method="POST" action="{% url 'users:signup' %}">
    {% csrf_token %}

    {% if form.none_field_errors %}
    {% for error in none_field_errors  %}
    <span class="field_error">{{error}}</span>
    {% endfor %}
    {% endif %}

    {% for field in form  %}
    <div class="input {% if field.errors %}has_error{% endif %}">
        {{field}}
        {% if field.errors %}
        {% for error in field.errors  %}
        <span class="error">{{error}}</span>
        {% endfor %}
        {% endif %}
    </div>

    {% endfor %}
    <button class="login_btn">회원 가입</button>
    <hr class="login_hr">
    <div class="go_to_signup">
        <span class="login_ask_have">이미 계정이 있으세요?</span>
        <a href="{% url 'core:login' %}"><span class="signup_link">로그인</span></a>
    </div>

</form>
{% endblock content %}
{% block bottom_menu %}{% endblock bottom_menu %}